// Generated by gencpp from file gwnav_ros_driver/GWNav.msg
// DO NOT EDIT!

#ifndef GWNAV_ROS_DRIVER_MESSAGE_GWNAV_H
#define GWNAV_ROS_DRIVER_MESSAGE_GWNAV_H

#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace gwnav_ros_driver
{
    template <class ContainerAllocator>
    struct GWNav_
    {
        typedef GWNav_<ContainerAllocator> Type;

        GWNav_()
            : header(), utc(), work_time(0), work_mode(0), self_test(0), angular_velocity(), linear_acceleration(), nue_velocity(), gyr_drift(), heaveing(0.0), height(0.0), longitude(0.0), latitude(0.0), roll(0.0), pitch(0.0), yaw(0.0), recv_pos_type(0), recv_position_state(false), recv_heading_state(false), nosv(0), recv_hdop(0.0), recv_nue_velocity(), recv_height(0.0), recv_longitude(0.0), recv_latitude(0.0), temperature(0.0), mag_heading(0.0), pre_height(0.0), gnss_heading(0.0), pps_time(0), itow(0)
        {
        }
        GWNav_(const ContainerAllocator &_alloc)
            : header(_alloc), utc(_alloc), work_time(0), work_mode(0), self_test(0), angular_velocity(_alloc), linear_acceleration(_alloc), nue_velocity(_alloc), gyr_drift(_alloc), heaveing(0.0), height(0.0), longitude(0.0), latitude(0.0), roll(0.0), pitch(0.0), yaw(0.0), recv_pos_type(0), recv_position_state(false), recv_heading_state(false), nosv(0), recv_hdop(0.0), recv_nue_velocity(_alloc), recv_height(0.0), recv_longitude(0.0), recv_latitude(0.0), temperature(0.0), mag_heading(0.0), pre_height(0.0), gnss_heading(0.0), pps_time(0), itow(0)
        {
            (void)_alloc;
        }

        typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
        _header_type header;

        typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _utc_type;
        _utc_type utc;

        typedef uint64_t _work_time_type;
        _work_time_type work_time;

        typedef uint64_t _work_mode_type;
        _work_mode_type work_mode;

        typedef uint64_t _self_test_type;
        _self_test_type self_test;

        typedef ::geometry_msgs::Vector3_<ContainerAllocator> _angular_velocity_type;
        _angular_velocity_type angular_velocity;

        typedef ::geometry_msgs::Vector3_<ContainerAllocator> _linear_acceleration_type;
        _linear_acceleration_type linear_acceleration;

        typedef ::geometry_msgs::Vector3_<ContainerAllocator> _nue_velocity_type;
        _nue_velocity_type nue_velocity;

        typedef ::geometry_msgs::Vector3_<ContainerAllocator> _gyr_drift_type;
        _gyr_drift_type gyr_drift;

        typedef double _heaveing_type;
        _heaveing_type heaveing;

        typedef double _height_type;
        _height_type height;

        typedef double _longitude_type;
        _longitude_type longitude;

        typedef double _latitude_type;
        _latitude_type latitude;

        typedef double _roll_type;
        _roll_type roll;

        typedef double _pitch_type;
        _pitch_type pitch;

        typedef double _yaw_type;
        _yaw_type yaw;

        typedef uint64_t _recv_pos_type_type;
        _recv_pos_type_type recv_pos_type;

        typedef uint8_t _recv_position_state_type;
        _recv_position_state_type recv_position_state;

        typedef uint8_t _recv_heading_state_type;
        _recv_heading_state_type recv_heading_state;

        typedef uint64_t _nosv_type;
        _nosv_type nosv;

        typedef double _recv_hdop_type;
        _recv_hdop_type recv_hdop;

        typedef ::geometry_msgs::Vector3_<ContainerAllocator> _recv_nue_velocity_type;
        _recv_nue_velocity_type recv_nue_velocity;

        typedef double _recv_height_type;
        _recv_height_type recv_height;

        typedef double _recv_longitude_type;
        _recv_longitude_type recv_longitude;

        typedef double _recv_latitude_type;
        _recv_latitude_type recv_latitude;

        typedef double _temperature_type;
        _temperature_type temperature;

        typedef double _mag_heading_type;
        _mag_heading_type mag_heading;

        typedef double _pre_height_type;
        _pre_height_type pre_height;

        typedef double _gnss_heading_type;
        _gnss_heading_type gnss_heading;

        typedef uint64_t _pps_time_type;
        _pps_time_type pps_time;

        typedef uint64_t _itow_type;
        _itow_type itow;

        typedef boost::shared_ptr<::gwnav_ros_driver::GWNav_<ContainerAllocator>> Ptr;
        typedef boost::shared_ptr<::gwnav_ros_driver::GWNav_<ContainerAllocator> const> ConstPtr;

    }; // struct GWNav_

    typedef ::gwnav_ros_driver::GWNav_<std::allocator<void>> GWNav;

    typedef boost::shared_ptr<::gwnav_ros_driver::GWNav> GWNavPtr;
    typedef boost::shared_ptr<::gwnav_ros_driver::GWNav const> GWNavConstPtr;

    // constants requiring out of line definition

    template <typename ContainerAllocator>
    std::ostream &operator<<(std::ostream &s, const ::gwnav_ros_driver::GWNav_<ContainerAllocator> &v)
    {
        ros::message_operations::Printer<::gwnav_ros_driver::GWNav_<ContainerAllocator>>::stream(s, "", v);
        return s;
    }

    template <typename ContainerAllocator1, typename ContainerAllocator2>
    bool operator==(const ::gwnav_ros_driver::GWNav_<ContainerAllocator1> &lhs, const ::gwnav_ros_driver::GWNav_<ContainerAllocator2> &rhs)
    {
        return lhs.header == rhs.header &&
               lhs.utc == rhs.utc &&
               lhs.work_time == rhs.work_time &&
               lhs.work_mode == rhs.work_mode &&
               lhs.self_test == rhs.self_test &&
               lhs.angular_velocity == rhs.angular_velocity &&
               lhs.linear_acceleration == rhs.linear_acceleration &&
               lhs.nue_velocity == rhs.nue_velocity &&
               lhs.gyr_drift == rhs.gyr_drift &&
               lhs.heaveing == rhs.heaveing &&
               lhs.height == rhs.height &&
               lhs.longitude == rhs.longitude &&
               lhs.latitude == rhs.latitude &&
               lhs.roll == rhs.roll &&
               lhs.pitch == rhs.pitch &&
               lhs.yaw == rhs.yaw &&
               lhs.recv_pos_type == rhs.recv_pos_type &&
               lhs.recv_position_state == rhs.recv_position_state &&
               lhs.recv_heading_state == rhs.recv_heading_state &&
               lhs.nosv == rhs.nosv &&
               lhs.recv_hdop == rhs.recv_hdop &&
               lhs.recv_nue_velocity == rhs.recv_nue_velocity &&
               lhs.recv_height == rhs.recv_height &&
               lhs.recv_longitude == rhs.recv_longitude &&
               lhs.recv_latitude == rhs.recv_latitude &&
               lhs.temperature == rhs.temperature &&
               lhs.mag_heading == rhs.mag_heading &&
               lhs.pre_height == rhs.pre_height &&
               lhs.gnss_heading == rhs.gnss_heading &&
               lhs.pps_time == rhs.pps_time &&
               lhs.itow == rhs.itow;
    }

    template <typename ContainerAllocator1, typename ContainerAllocator2>
    bool operator!=(const ::gwnav_ros_driver::GWNav_<ContainerAllocator1> &lhs, const ::gwnav_ros_driver::GWNav_<ContainerAllocator2> &rhs)
    {
        return !(lhs == rhs);
    }

} // namespace gwnav_ros_driver

namespace ros
{
    namespace message_traits
    {

        template <class ContainerAllocator>
        struct IsMessage<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
            : TrueType
        {
        };

        template <class ContainerAllocator>
        struct IsMessage<::gwnav_ros_driver::GWNav_<ContainerAllocator> const>
            : TrueType
        {
        };

        template <class ContainerAllocator>
        struct IsFixedSize<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
            : FalseType
        {
        };

        template <class ContainerAllocator>
        struct IsFixedSize<::gwnav_ros_driver::GWNav_<ContainerAllocator> const>
            : FalseType
        {
        };

        template <class ContainerAllocator>
        struct HasHeader<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
            : TrueType
        {
        };

        template <class ContainerAllocator>
        struct HasHeader<::gwnav_ros_driver::GWNav_<ContainerAllocator> const>
            : TrueType
        {
        };

        template <class ContainerAllocator>
        struct MD5Sum<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
        {
            static const char *value()
            {
                return "35416ec04c26f0e8dbabee1ffd2668e0";
            }

            static const char *value(const ::gwnav_ros_driver::GWNav_<ContainerAllocator> &) { return value(); }
            static const uint64_t static_value1 = 0x35416ec04c26f0e8ULL;
            static const uint64_t static_value2 = 0xdbabee1ffd2668e0ULL;
        };

        template <class ContainerAllocator>
        struct DataType<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
        {
            static const char *value()
            {
                return "gwnav_ros_driver/GWNav";
            }

            static const char *value(const ::gwnav_ros_driver::GWNav_<ContainerAllocator> &) { return value(); }
        };

        template <class ContainerAllocator>
        struct Definition<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
        {
            static const char *value()
            {
                return "Header header\n"
                       "string utc\n"
                       "uint64 work_time\n"
                       "uint64 work_mode\n"
                       "uint64 self_test\n"
                       "geometry_msgs/Vector3 angular_velocity\n"
                       "geometry_msgs/Vector3 linear_acceleration\n"
                       "geometry_msgs/Vector3 nue_velocity\n"
                       "geometry_msgs/Vector3 gyr_drift\n"
                       "float64 heaveing\n"
                       "float64 height\n"
                       "float64 longitude\n"
                       "float64 latitude\n"
                       "float64 roll\n"
                       "float64 pitch\n"
                       "float64 yaw\n"
                       "uint64 recv_pos_type\n"
                       "bool recv_position_state\n"
                       "bool recv_heading_state\n"
                       "uint64 nosv\n"
                       "float64 recv_hdop\n"
                       "geometry_msgs/Vector3  recv_nue_velocity\n"
                       "float64 recv_height\n"
                       "float64 recv_longitude\n"
                       "float64 recv_latitude\n"
                       "float64 temperature\n"
                       "float64 mag_heading\n"
                       "float64 pre_height\n"
                       "float64 gnss_heading\n"
                       "uint64 pps_time\n"
                       "uint64 itow\n"
                       "================================================================================\n"
                       "MSG: std_msgs/Header\n"
                       "# Standard metadata for higher-level stamped data types.\n"
                       "# This is generally used to communicate timestamped data \n"
                       "# in a particular coordinate frame.\n"
                       "# \n"
                       "# sequence ID: consecutively increasing ID \n"
                       "uint32 seq\n"
                       "#Two-integer timestamp that is expressed as:\n"
                       "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
                       "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
                       "# time-handling sugar is provided by the client library\n"
                       "time stamp\n"
                       "#Frame this data is associated with\n"
                       "string frame_id\n"
                       "\n"
                       "================================================================================\n"
                       "MSG: geometry_msgs/Vector3\n"
                       "# This represents a vector in free space. \n"
                       "# It is only meant to represent a direction. Therefore, it does not\n"
                       "# make sense to apply a translation to it (e.g., when applying a \n"
                       "# generic rigid transformation to a Vector3, tf2 will only apply the\n"
                       "# rotation). If you want your data to be translatable too, use the\n"
                       "# geometry_msgs/Point message instead.\n"
                       "\n"
                       "float64 x\n"
                       "float64 y\n"
                       "float64 z\n";
            }

            static const char *value(const ::gwnav_ros_driver::GWNav_<ContainerAllocator> &) { return value(); }
        };

    } // namespace message_traits
} // namespace ros

namespace ros
{
    namespace serialization
    {

        template <class ContainerAllocator>
        struct Serializer<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
        {
            template <typename Stream, typename T>
            inline static void allInOne(Stream &stream, T m)
            {
                stream.next(m.header);
                stream.next(m.utc);
                stream.next(m.work_time);
                stream.next(m.work_mode);
                stream.next(m.self_test);
                stream.next(m.angular_velocity);
                stream.next(m.linear_acceleration);
                stream.next(m.nue_velocity);
                stream.next(m.gyr_drift);
                stream.next(m.heaveing);
                stream.next(m.height);
                stream.next(m.longitude);
                stream.next(m.latitude);
                stream.next(m.roll);
                stream.next(m.pitch);
                stream.next(m.yaw);
                stream.next(m.recv_pos_type);
                stream.next(m.recv_position_state);
                stream.next(m.recv_heading_state);
                stream.next(m.nosv);
                stream.next(m.recv_hdop);
                stream.next(m.recv_nue_velocity);
                stream.next(m.recv_height);
                stream.next(m.recv_longitude);
                stream.next(m.recv_latitude);
                stream.next(m.temperature);
                stream.next(m.mag_heading);
                stream.next(m.pre_height);
                stream.next(m.gnss_heading);
                stream.next(m.pps_time);
                stream.next(m.itow);
            }

            ROS_DECLARE_ALLINONE_SERIALIZER
        }; // struct GWNav_

    } // namespace serialization
} // namespace ros

namespace ros
{
    namespace message_operations
    {

        template <class ContainerAllocator>
        struct Printer<::gwnav_ros_driver::GWNav_<ContainerAllocator>>
        {
            template <typename Stream>
            static void stream(Stream &s, const std::string &indent, const ::gwnav_ros_driver::GWNav_<ContainerAllocator> &v)
            {
                s << indent << "header: ";
                s << std::endl;
                Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
                s << indent << "utc: ";
                Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.utc);
                s << indent << "work_time: ";
                Printer<uint64_t>::stream(s, indent + "  ", v.work_time);
                s << indent << "work_mode: ";
                Printer<uint64_t>::stream(s, indent + "  ", v.work_mode);
                s << indent << "self_test: ";
                Printer<uint64_t>::stream(s, indent + "  ", v.self_test);
                s << indent << "angular_velocity: ";
                s << std::endl;
                Printer<::geometry_msgs::Vector3_<ContainerAllocator>>::stream(s, indent + "  ", v.angular_velocity);
                s << indent << "linear_acceleration: ";
                s << std::endl;
                Printer<::geometry_msgs::Vector3_<ContainerAllocator>>::stream(s, indent + "  ", v.linear_acceleration);
                s << indent << "nue_velocity: ";
                s << std::endl;
                Printer<::geometry_msgs::Vector3_<ContainerAllocator>>::stream(s, indent + "  ", v.nue_velocity);
                s << indent << "gyr_drift: ";
                s << std::endl;
                Printer<::geometry_msgs::Vector3_<ContainerAllocator>>::stream(s, indent + "  ", v.gyr_drift);
                s << indent << "heaveing: ";
                Printer<double>::stream(s, indent + "  ", v.heaveing);
                s << indent << "height: ";
                Printer<double>::stream(s, indent + "  ", v.height);
                s << indent << "longitude: ";
                Printer<double>::stream(s, indent + "  ", v.longitude);
                s << indent << "latitude: ";
                Printer<double>::stream(s, indent + "  ", v.latitude);
                s << indent << "roll: ";
                Printer<double>::stream(s, indent + "  ", v.roll);
                s << indent << "pitch: ";
                Printer<double>::stream(s, indent + "  ", v.pitch);
                s << indent << "yaw: ";
                Printer<double>::stream(s, indent + "  ", v.yaw);
                s << indent << "recv_pos_type: ";
                Printer<uint64_t>::stream(s, indent + "  ", v.recv_pos_type);
                s << indent << "recv_position_state: ";
                Printer<uint8_t>::stream(s, indent + "  ", v.recv_position_state);
                s << indent << "recv_heading_state: ";
                Printer<uint8_t>::stream(s, indent + "  ", v.recv_heading_state);
                s << indent << "nosv: ";
                Printer<uint64_t>::stream(s, indent + "  ", v.nosv);
                s << indent << "recv_hdop: ";
                Printer<double>::stream(s, indent + "  ", v.recv_hdop);
                s << indent << "recv_nue_velocity: ";
                s << std::endl;
                Printer<::geometry_msgs::Vector3_<ContainerAllocator>>::stream(s, indent + "  ", v.recv_nue_velocity);
                s << indent << "recv_height: ";
                Printer<double>::stream(s, indent + "  ", v.recv_height);
                s << indent << "recv_longitude: ";
                Printer<double>::stream(s, indent + "  ", v.recv_longitude);
                s << indent << "recv_latitude: ";
                Printer<double>::stream(s, indent + "  ", v.recv_latitude);
                s << indent << "temperature: ";
                Printer<double>::stream(s, indent + "  ", v.temperature);
                s << indent << "mag_heading: ";
                Printer<double>::stream(s, indent + "  ", v.mag_heading);
                s << indent << "pre_height: ";
                Printer<double>::stream(s, indent + "  ", v.pre_height);
                s << indent << "gnss_heading: ";
                Printer<double>::stream(s, indent + "  ", v.gnss_heading);
                s << indent << "pps_time: ";
                Printer<uint64_t>::stream(s, indent + "  ", v.pps_time);
                s << indent << "itow: ";
                Printer<uint64_t>::stream(s, indent + "  ", v.itow);
            }
        };

    } // namespace message_operations
} // namespace ros

#endif // GWNAV_ROS_DRIVER_MESSAGE_GWNAV_H
